version: "3.2"
services:
  mongodb:
    image: "bitnami/mongodb:latest"
    volumes:
      - "mongodb_data:/bitnami"
  scichat-loopback:
    image: "dacat/scichat-loopback:test"
    command: ["./wait-for-it.sh", "mongodb:27017", "--", "npm", "test"]
    environment:
      - SYNAPSE_BOT_NAME
      - SYNAPSE_BOT_PASSWORD
    depends_on:
      - mongodb
volumes:
  mongodb_data:
    driver: local
