version: "3.2"
services:

  scichat-loopback:
    build:
      context: .
      dockerfile: CI/ESS/Dockerfile.test
    environment:
      SYNAPSE_BOT_NAME: "BotNameGoesHere"
      SYNAPSE_BOT_PASSWORD: "BotPasswordGoesHere"
