# Check out https://hub.docker.com/_/node to select a new base image
FROM node:16-alpine

RUN apk update && apk upgrade && apk add --no-cache bash git

# Create app directory (with user `node`)
WORKDIR /home/node/app
RUN chown -R node:node /home/node/app
USER node

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY --chown=node:node package*.json /home/node/app/
COPY --chown=node:node .snyk /home/node/app/
RUN npm ci

# Bundle app source code
COPY --chown=node:node . /home/node/app/
COPY --chown=node:node CI/ESS/.env /home/node/app/
COPY --chown=node:node CI/ESS/wait.sh /home/node/app/
RUN chmod +x /home/node/app/wait.sh

RUN npm run build

# Bind to all network interfaces so that it can be mapped to the host OS
ENV HOST=0.0.0.0 PORT=3050

EXPOSE ${PORT}
CMD [ "./wait.sh" ]
