FROM node:14-alpine

RUN apk update && apk upgrade && apk add --no-cache git

ENV PORT=3030
EXPOSE 3030

# Prepare app directory
WORKDIR /usr/src/app
COPY package*.json /usr/src/app/
COPY .snyk /usr/src/app/

# set up local user to avoid running as root
RUN chown -R node:node /usr/src/app
USER node

# Install our packages
RUN npm ci

# Copy the rest of our application, node_modules is ignored via .dockerignore
COPY --chown=node:node . /usr/src/app

# Start the app
CMD [ "node", "." ]
