name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: test
        run: |
          cp CI/ESS/datasources.test.json server/datasources.json
          cp CI/ESS/docker-compose.test.yaml docker-compose.yaml
          docker-compose down --remove-orphans
          docker-compose pull
          docker-compose up --build --exit-code-from scichat-loopback
          docker-compose down

  gitlab:
    name: Build and deploy
    needs: [test]
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-loopback
    steps:
      - name: trigger Job
        uses: appleboy/gitlab-ci-action@master
        with:
          token: ${{ secrets.GITLAB_TOKEN }}
          project_id: 1981
          ref: "master"
          host: "https://gitlab.esss.lu.se"
          debug: true

